cwlVersion: v1.2
class: CommandLineTool
id: scdblfinder-rmd
doc: "Run custom QC on 10X output"

requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: "pgc-images.sbgenomics.com/brownm28/scdblfinder:1.8.0"
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: scDblFinder.Rmd
        entry:
          $include: ../scripts/scDblFinder.Rmd
  - class: ResourceRequirement
    coresMin: 8
    ramMin: 16000

baseCommand: [Rscript, -e]
arguments:
  - position: 1
    shellQuote: false
    valueFrom: >-
      "rmarkdown::render('scDblFinder.Rmd', clean = TRUE,
            params=list(results_dir='.', 
                        data_path='$(inputs.seurat_raw_object.path)', 
                        sample_name='$(inputs.sample_name)'
                        ))"
inputs:
  seurat_raw_object: { type: File, doc: "Sueurat RDS from align/qc workflow" }
  sample_name: { type: string }

outputs:
  result_dir:
    type: Directory
    outputBinding:
      loadListing: deep_listing
      glob: 'scDblFinder-$(inputs.sample_name)'
    doc: "Dir containing all files that were generated by the notebook"
