cwlVersion: v1.0
class: CommandLineTool
id: seurat
doc: "Run Seurat analysis on 10x output"

requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: 'pgc-images.sbgenomics.com/d3b-bixu/soupx_r:4.1.0_SoupX'
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: seurat_analysis.R
        entry:
          $include: ../scripts/seurat_analysis.R

baseCommand: [Rscript]

arguments:
  - position: 1
    shellQuote: false
    valueFrom: >-
     seurat_analysis.R
  - position: 3
    shellQuote: false
    valueFrom: >-
      && tar -czf $(inputs.output_basename).tar.gz $(inputs.output_basename)

inputs:
  size: {type: "int?", inputBinding: {prefix: --size, position: 2}, default: 500, doc: "Plot size, plot area will be a square with side length of size"}
  name: {type: "string?", inputBinding: {prefix: --name, position: 2}, doc: "Project name, used internally by Seurat"}
  out_size: {type: "int?", inputBinding: {prefix: --out_size, position: 2}, doc: "Number of genes to include in the cluster output file."}
  input_data: {type: File, inputBinding: {prefix: --data, position: 2}, doc: "Input data, can be matrix tarball, cellragner h5, or Seurat object rds file"}
  output_basename: {type: string, inputBinding: {prefix: --out, position: 2}, doc: "name of output directory"}
  min_features: {type: "int?", inputBinding: {prefix: --min_features, position: 2}, default: 200, doc: "Minimum number of genes observed in a cell to retain"}
  max_features: {type: "int?", inputBinding: {prefix: --max_features, position: 2}, default: 2500, doc: "Maximum number of genes observed in a cell to retain"}
  max_mt: {type: "int?", inputBinding: {prefix: --max_mt, position: 2}, default: 5, doc: "Maximum mitochondrial percentage observed in a cell to retain"}
  norm_method: {type: "string?", inputBinding: {prefix: --norm_method, position: 2}, default: "LogNormalize", doc: "Normalization to apply to counts (LogNormalize, CLR, RC)"}
  retain_features: {type: "int?", inputBinding: {prefix: --retain_features, position: 2}, default: 2000, doc: "Number of most-variable features to initially retain"}
  nheatmap: {type: "int?", inputBinding: {prefix: --nheatmap, position: 2}, default: 10, doc: "Number of principal components for which to produce heatmaps"}
  num_pcs: {type: "int?", inputBinding: {prefix: --num_pcs, position: 2}, default: 10, doc: "Number of principal components to retain for clustering"}
  pc_cut: {type: "float?", inputBinding: {prefix: --pc_cut, position: 2}, default: 0.05, doc: "p-value cutoff for determing the number of prinicipal components to retrain for clustering"}
  knn_granularity: {type: "float?", inputBinding: {prefix: --knn_granularity, position: 2}, default: 0.5, doc: "KNN clustering granularity parameter"}
  min_cells: {type: "int?", inputBinding: {prefix: --min_cells, position: 2}, default: 3, doc: "Minimum number of cells a feature must be present in to be retained"}
  min_samples: {type: "float?", inputBinding: {prefix: --min_samples, position: 2}, default: 100, doc: "Minimum number of samples to continue analysis, used after QC filtering"}

outputs:
  tarball:
    type: File
    outputBinding:
      glob: $(inputs.output_basename).tar.gz
    doc: "Tarball containing all files that were generated by Seurat"
