cwlVersion: v1.0
class: CommandLineTool
id: seurat
doc: "Run Seurat analysis on 10x output"

requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: 'satijalab/seurat:3.2.0'
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: seurat_analysis.R
        entry:
          $include: ../scripts/seurat_analysis.R

baseCommand: [Rscript]

arguments:
  - position: 1
    shellQuote: false
    valueFrom: >-
     seurat_analysis.R --data $(inputs.input_data.path) --out $(inputs.output_basename)
     --min_features $(inputs.min_features) --max_features $(inputs.max_features) --max_mt $(inputs.max_mt)
     --norm_method $(inputs.norm_method) --retain_features $(inputs.retain_features) --nheatmap $(inputs.nheatmap)
     --num_pcs $(inputs.num_pcs) --knn_granularity $(inputs.knn_granularity)
     ${
       if (inputs.name != null){
         return "--name " + inputs.name;
       }
       else{
         return "";
       }
     }
     ${
       if (inputs.size != null){
         return "--size " + inputs.size;
       }
       else{
         return "";
       }
     }
     ${
       if (inputs.out_size != null){
         return "--out_size " + inputs.out_size;
       }
       else{
         return "";
       }
     }
     && tar -czf $(inputs.output_basename).tar.gz $(inputs.output_basename)

inputs:
  size: {type: "int?", default: 500, doc: "Plot size, plot area will be a square with side length of size"}
  name: {type: "string?", doc: "Project name, used internally by Seurat"}
  out_size: {type: "int?", doc: "Number of genes to include in the cluster output file."}
  input_data: {type: File, doc: "Input data, can be matrix tarball, cellragner h5, or Seurat object rds file"}
  output_basename: {type: string, doc: "name of output directory"}
  min_features: {type: "int?", default: 200, doc: "Minimum number of genes observed in a cell to retain"}
  max_features: {type: "int?", default: 2500, doc: "Maximum number of genes observed in a cell to retain"}
  max_mt: {type: "int?", default: 5, doc: "Maximum mitochondrial percentage observed in a cell to retain"}
  norm_method: {type: "string?", default: "LogNormalize", doc: "Normalization to apply to counts (LogNormalize, CLR, RC)"}
  retain_features: {type: "int?", default: 2000, doc: "Number of most-variable features to initially retain"}
  nheatmap: {type: "int?", default: 10, doc: "Number of principal components for which to produce heatmaps"}
  num_pcs: {type: "int?", default: 10, doc: "Number of principal components to retain for clustering"}
  knn_granularity: {type: "float?", default: 0.5, doc: "KNN clustering granularity parameter"}

outputs:
  tarball:
    type: File
    outputBinding:
      glob: $(inputs.output_basename).tar.gz
    doc: "Tarball containing all files that were generated by Seurat"
