cwlVersion: v1.2
class: CommandLineTool
id: seurat-qc
doc: "Run custom QC on 10X output"

requirements:
  - class: ShellCommandRequirement
  - class: DockerRequirement
    dockerPull: 'pgc-images.sbgenomics.com/brownm28/scrna_qc:v1.0.0'
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: 01_Seurat_QC.Rmd
        entry:
          $include: ../scripts/01_Seurat_QC.Rmd
  - class: ResourceRequirement
    coresMin: 8
    ramMin: 16000

baseCommand: [Rscript, -e]

arguments:
  - position: 1
    shellQuote: false
    valueFrom: >-
      "rmarkdown::render('01_Seurat_QC.Rmd', clean = TRUE,
            params=list(scooter_path = '/scooter', 
                        out_path='.', 
                        data_path='$(inputs.filtered_bc_matrix_dir.path)', 
                        sample_name='$(inputs.sample_name)'))"
  - position: 2
    shellQuote: false
    valueFrom: >-
      && mv 01_Seurat_QC.html Seurat_QC-$(inputs.sample_name).html


inputs:
  filtered_bc_matrix_dir: { type: Directory}
  sample_name: {type: string }
outputs:
  result_dir:
    type: Directory
    outputBinding:
      glob: 'Seurat_QC-$(inputs.sample_name)'
    doc: "Dir containing all files that were generated by Seurat"
  summary_html:
    type: File
    outputBinding:
      glob: "*.html"
    doc: "html file with qc results summary"
